import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import styles from '../styles/Home.module.scss'
// import styles from '../styles/custom.scss'
import { Button } from 'react-bootstrap'
import Col from 'react-bootstrap/Col';
import Form from 'react-bootstrap/Form';
import Row from 'react-bootstrap/Row';
import banner from '../assets/images/home-banner.PNG'


export default function Home() {
  const mainImage = "../assets/images/home-banner.PNG"
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Form className="w-100 my-lg-5 my-sm-5 my-5  px-4 d-none">
          <Row>
            <Col xs={12} lg={5}>
              <div >
                <div className="d-flex justify-content-center align-items-center">
                  <i className="fa fa-clone me-2" aria-hidden="true">Icon</i>
                  <Form.Control placeholder="City" />
                </div>
              </div>
            </Col>
            <Col xs={12} lg={4}>
            </Col>
            <Col xs={12} lg={3}>
              <div className="d-flex justify-content-lg-end mt-2">
                <div className="custom-control custom-switch">
                  <input type="checkbox" className="custom-control-input" id="customSwitch1" />
                  <label className="custom-control-label ms-2" htmlFor="customSwitch1">Edit mode</label>
                </div>
                <a href="" className="px-4">Add task +</a>
              </div>
            </Col>
          </Row>
        </Form>
        <Header />
        <Row className="w-100 mt-4">
          <Col xs={12} lg={6}>
            <div className="pe-3">
              <h1 className="fw-bolder px-5 pt-5" style={{ fontSize: '65px' }}>Don't wanna Make you have A bad day</h1>
              <h3 className="px-5 pt-3 text-muted" >Our job is delivering a delicious food with fast, free delivery and easy. </h3>
              <div className="px-5 pt-4">
                <Button variant="warning rounded-pill px-4 text-light fw-bold">Order Now</Button>
                <Button variant="outline-warning rounded-pill px-4 mx-lg-3 mx-md-3 fw-bold">How to Order</Button>
              </div>
            </div>
          </Col>
          <Col xs={12} lg={6} className="text-lg-end"><Image src={banner} alt="Picture of the author"
            width={500}
            height={500} /></Col>
        </Row>
        <h1 className={styles.title}>
          Hello World!
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
